name: Unittest
run-name: Unittest
on: [push]
jobs:
  Unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Run unittest
        run: |
          python3 ${{ github.workspace }}/App.py
      - run: echo "ğŸ This job's status is ${{ job.status }}."
